### ISSUE TITLE
InlineHelp: rebuild with Popover component

### ISSUE THREAD

**Issue by athulvraj** [SAP/fundamental-react#1014] opened 2020-05-13 14:25 UTC

**Comment by JaySardhara** [comment] 2020-05-16 03:34
@athulvraj is this duplicate of #920 ?

**Comment by jbadan** [comment] 2020-05-18 14:54
@JaySardhara This is the issue to track the work associated with updating InlineHelp - it will solve several open issues so it was easier for tracking to create this.

**Comment by jbadan** [comment] 2020-09-01 21:38
fixed https://github.com/SAP/fundamental-react/pull/1094

**Closed by jbadan** 2020-09-01 21:38 UTC
Labels: bug
